# Generated by Django 3.2.8 on 2021-10-07 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='condition',
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('New', '1'), ('Used', '2')], default=0, max_length=100),
            preserve_default=False,
        ),
    ]
