# Generated by Django 3.2.8 on 2021-10-08 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20211008_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='imahe',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
